apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qc5fma9i6-go 
  janus-idp.io/tekton: qc5fma9i6-go
  backstage.io/kubernetes-id: qc5fma9i6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qc5fma9i6-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  